[project]
name = "mambacompressor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "accelerate>=0.26.0",
    "gdown>=5.2.0",
    "pandas>=2.2.3",
    "torch>=2.6.0",
    "transformers>=4.49.0",
]
